import dell1 from "../../assests/electronics/dell/dell1.jfif";
import dell2 from "../../assests/electronics/dell/dell2.jpg";
import dell3 from "../../assests/electronics/dell/dell3.jfif";
export function getDellData(param) {
    return [
      {
        id: 1000,
        name: "Dell Aspiron",
        prodimage1: dell1,
        prodimage2: dell1,
        prodimage3: dell1,
        prodimage4: dell1,
        prodimage5: dell1,
        prodimage6: dell1,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
      {
        id: 1001,
        name: "Dell Inspire",
        prodimage1: dell2,
        prodimage2: dell2,
        prodimage3: dell2,
        prodimage4: dell2,
        prodimage5: dell2,
        prodimage6: dell2,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$480",
        quantity: 0,
      },
      {
        id: 1003,
        name: "Dell Aspiron 5 pro",
        prodimage1: dell3,
        prodimage2: dell3,
        prodimage3: dell3,
        prodimage4: dell3,
        prodimage5: dell3,
        prodimage6: dell3,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
      {
        id: 1004,
        name: "Dell Inspire",
        prodimage1: dell2,
        prodimage2: dell2,
        prodimage3: dell2,
        prodimage4: dell2,
        prodimage5: dell2,
        prodimage6: dell2,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$480",
        quantity: 0,
      },
      {
        id: 1005,
        name: "Dell Aspiron 5 pro",
        prodimage1: dell3,
        prodimage2: dell3,
        prodimage3: dell3,
        prodimage4: dell3,
        prodimage5: dell3,
        prodimage6: dell3,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
    ];
}