import asus from "../../assests/electronics/asus.jpg"
import asus2 from "../../assests/electronics/asus/asus2.jfif"
import asus3 from "../../assests/electronics/asus/asus3.jfif";
export function getElectronicData(param) {
    return [
      {
        id: 0,
        name: "asus k15",
        prodimage1: asus,
        prodimage2: asus,
        prodimage3: asus,
        prodimage4: asus,
        prodimage5: asus,
        prodimage6: asus,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
      {
        id: 1,
        name: "asus k10",
        prodimage1: asus2,
        prodimage2: asus2,
        prodimage3: asus2,
        prodimage4: asus2,
        prodimage5: asus2,
        prodimage6: asus2,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
      {
        id: 2,
        name: "asus oled",
        prodimage1: asus3,
        prodimage2: asus3,
        prodimage3: asus3,
        prodimage4: asus3,
        prodimage5: asus3,
        prodimage6: asus3,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
      {
        id: 3,
        name: "asus-rog",
        prodimage1: asus,
        prodimage2: asus,
        prodimage3: asus,
        prodimage4: asus,
        prodimage5: asus,
        prodimage6: asus,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
      {
        id: 4,
        name: "asus",
        prodimage1: asus2,
        prodimage2: asus2,
        prodimage3: asus2,
        prodimage4: asus2,
        prodimage5: asus2,
        prodimage6: asus2,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
    ];
}