import lenvo1 from "../../assests/electronics/lenvo/lenvo1.jpg";
import lenvo2 from "../../assests/electronics/lenvo/lenvo2.png";
import lenvo3 from "../../assests/electronics/lenvo/lenvo3.jpg";
export function getLenvoData(props) {
    return [
      {
        id: 1100,
        name: "Lenvo Aspiron",
        prodimage1: lenvo1,
        prodimage2: lenvo1,
        prodimage3: lenvo1,
        prodimage4: lenvo1,
        prodimage5: lenvo1,
        prodimage6: lenvo1,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
      {
        id: 1101,
        name: "Lenvo Aspiron",
        prodimage1: lenvo2,
        prodimage2: lenvo2,
        prodimage3: lenvo2,
        prodimage4: lenvo2,
        prodimage5: lenvo2,
        prodimage6: lenvo2,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$480",
        quantity: 0,
      },
      {
        id: 1103,
        name: "Lenvo Aspiron",
        prodimage1: lenvo3,
        prodimage2: lenvo3,
        prodimage3: lenvo3,
        prodimage4: lenvo3,
        prodimage5: lenvo3,
        prodimage6: lenvo3,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$480",
        quantity: 0,
      },
      {
        id: 1104,
        name: "Lenvo Aspiron",
        prodimage1: lenvo1,
        prodimage2: lenvo1,
        prodimage3: lenvo1,
        prodimage4: lenvo1,
        prodimage5: lenvo1,
        prodimage6: lenvo1,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
      {
        id: 1105,
        name: "Lenvo Aspiron",
        prodimage1: lenvo2,
        prodimage2: lenvo2,
        prodimage3: lenvo2,
        prodimage4: lenvo2,
        prodimage5: lenvo2,
        prodimage6: lenvo2,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$480",
        quantity: 0,
      },
      {
        id: 1106,
        name: "Lenvo Aspiron",
        prodimage1: lenvo3,
        prodimage2: lenvo3,
        prodimage3: lenvo3,
        prodimage4: lenvo3,
        prodimage5: lenvo3,
        prodimage6: lenvo3,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$480",
        quantity: 0,
      },
    ];
}