import asus from "../assests/electronics/asus.jpg"
import asus2 from "../assests/electronics/asus/asus2.jfif";
import asus3 from "../assests/electronics/asus/asus3.jfif";
import denim from "../assests/clothes/denim.jpeg";
import toy from "../assests/kids/toy.jpg";
import dell1 from "../assests/electronics/dell/dell1.jfif"
import dell2 from "../assests/electronics/dell/dell2.jpg";
import dell3 from "../assests/electronics/dell/dell3.jfif";
import lenvo1 from "../assests/electronics/lenvo/lenvo1.jpg";
import lenvo2 from "../assests/electronics/lenvo/lenvo2.png";
import lenvo3 from "../assests/electronics/lenvo/lenvo3.jpg";

export function getBrowsingData(param) {
  return [
    {
      id: 0,
      name: "asus k15",
      prodimage1: asus,
      prodimage2: asus,
      prodimage3: asus,
      prodimage4: asus,
      prodimage5: asus,
      prodimage6: asus,
      desc: {
        point1: "Do Check Partner offer section for Exciting offers from HP",
        point2:
          "Processor: Intel Core i3-1115G4 (up to 4.1 GHz with Intel Turbo Boost Technology(2g),6 MB L3 cache, 2 cores)|Memory: 8 GB DDR4-3200 SDRAM (1 x 8 GB)| Storage: 512 GB PCIe NVMe M.2 SSD",
        point3:
          "Display & Graphics : 39.6 cm (15.6) diagonal, FHD, micro-edge,anti-glare, 250 nits, 141 ppi, 45%NTSC |Graphics: Intel UHD Graphics",
        point4:
          "Operating System & Preinstalled Software: Windows 11 Home 64 Plus Single Language | Microsoft Office Home & Student 2021| McAfee LiveSafe (30 days free trial as default) |Pre-installed Alexa built-in- Your life simplified with Alexa. Just ask Alexa to check your calendar, create to-do lists, shopping lists, play music, set reminders, get latest news and control smart home.",
        point5:
          "Ports: 1 SuperSpeed USB Type-C 5Gbps signaling rate, 2 SuperSpeed USB Type-A 5Gbps signaling rate, 1 headphone/microphone combo, 1 AC smart pin, 1 HDMI 1.4b",
      },
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 1,
      name: "asus k10",
      prodimage1: asus2,
      prodimage2: asus2,
      prodimage3: asus2,
      prodimage4: asus2,
      prodimage5: asus2,
      prodimage6: asus2,
      desc: {
        point1: "Do Check Partner offer section for Exciting offers from HP",
        point2:
          "Processor: Intel Core i3-1115G4 (up to 4.1 GHz with Intel Turbo Boost Technology(2g),6 MB L3 cache, 2 cores)|Memory: 8 GB DDR4-3200 SDRAM (1 x 8 GB)| Storage: 512 GB PCIe NVMe M.2 SSD",
        point3:
          "Display & Graphics : 39.6 cm (15.6) diagonal, FHD, micro-edge,anti-glare, 250 nits, 141 ppi, 45%NTSC |Graphics: Intel UHD Graphics",
        point4:
          "Operating System & Preinstalled Software: Windows 11 Home 64 Plus Single Language | Microsoft Office Home & Student 2021| McAfee LiveSafe (30 days free trial as default) |Pre-installed Alexa built-in- Your life simplified with Alexa. Just ask Alexa to check your calendar, create to-do lists, shopping lists, play music, set reminders, get latest news and control smart home.",
        point5:
          "Ports: 1 SuperSpeed USB Type-C 5Gbps signaling rate, 2 SuperSpeed USB Type-A 5Gbps signaling rate, 1 headphone/microphone combo, 1 AC smart pin, 1 HDMI 1.4b",
      },
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 2,
      name: "asus oled",
      prodimage1: asus3,
      prodimage2: asus3,
      prodimage3: asus3,
      prodimage4: asus3,
      prodimage5: asus3,
      prodimage6: asus3,
      desc: {
        point1: "Do Check Partner offer section for Exciting offers from HP",
        point2:
          "Processor: Intel Core i3-1115G4 (up to 4.1 GHz with Intel Turbo Boost Technology(2g),6 MB L3 cache, 2 cores)|Memory: 8 GB DDR4-3200 SDRAM (1 x 8 GB)| Storage: 512 GB PCIe NVMe M.2 SSD",
        point3:
          "Display & Graphics : 39.6 cm (15.6) diagonal, FHD, micro-edge,anti-glare, 250 nits, 141 ppi, 45%NTSC |Graphics: Intel UHD Graphics",
        point4:
          "Operating System & Preinstalled Software: Windows 11 Home 64 Plus Single Language | Microsoft Office Home & Student 2021| McAfee LiveSafe (30 days free trial as default) |Pre-installed Alexa built-in- Your life simplified with Alexa. Just ask Alexa to check your calendar, create to-do lists, shopping lists, play music, set reminders, get latest news and control smart home.",
        point5:
          "Ports: 1 SuperSpeed USB Type-C 5Gbps signaling rate, 2 SuperSpeed USB Type-A 5Gbps signaling rate, 1 headphone/microphone combo, 1 AC smart pin, 1 HDMI 1.4b",
      },
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 3,
      name: "asus-rog",
      prodimage1: asus,
      prodimage2: asus,
      prodimage3: asus,
      prodimage4: asus,
      prodimage5: asus,
      prodimage6: asus,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 4,
      name: "asus",
      prodimage1: asus2,
      prodimage2: asus2,
      prodimage3: asus2,
      prodimage4: asus2,
      prodimage5: asus2,
      prodimage6: asus2,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },

    {
      id: 10,
      name: "denim",
      prodimage1: denim,
      prodimage2: denim,
      prodimage3: denim,
      prodimage4: denim,
      prodimage5: denim,
      prodimage6: denim,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 11,
      name: "asus k1",
      prodimage1: denim,
      prodimage2: denim,
      prodimage3: denim,
      prodimage4: denim,
      prodimage5: denim,
      prodimage6: denim,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 12,
      name: "asus k15",
      prodimage1: denim,
      prodimage2: denim,
      prodimage3: denim,
      prodimage4: denim,
      prodimage5: denim,
      prodimage6: denim,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 13,
      name: "asus k15",
      prodimage1: denim,
      prodimage2: denim,
      prodimage3: denim,
      prodimage4: denim,
      prodimage5: denim,
      prodimage6: denim,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 14,
      name: "asus k15",
      prodimage1: denim,
      prodimage2: denim,
      prodimage3: denim,
      prodimage4: denim,
      prodimage5: denim,
      prodimage6: denim,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },

    {
      id: 20,
      name: "transformer",
      prodimage1: toy,
      prodimage2: toy,
      prodimage3: toy,
      prodimage4: toy,
      prodimage5: toy,
      prodimage6: toy,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 21,
      name: "asus k1",
      prodimage1: toy,
      prodimage2: toy,
      prodimage3: toy,
      prodimage4: toy,
      prodimage5: toy,
      prodimage6: toy,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 22,
      name: "asus k15",
      prodimage1: toy,
      prodimage2: toy,
      prodimage3: toy,
      prodimage4: toy,
      prodimage5: toy,
      prodimage6: toy,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 23,
      name: "asus k15",
      prodimage1: toy,
      prodimage2: toy,
      prodimage3: toy,
      prodimage4: toy,
      prodimage5: toy,
      prodimage6: toy,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 24,
      name: "asus k15",
      prodimage1: toy,
      prodimage2: toy,
      prodimage3: toy,
      prodimage4: toy,
      prodimage5: toy,
      prodimage6: toy,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },

    {
      id: 1000,
      name: "Dell Aspiron",
      prodimage1: dell1,
      prodimage2: dell1,
      prodimage3: dell1,
      prodimage4: dell1,
      prodimage5: dell1,
      prodimage6: dell1,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 1001,
      name: "Dell Inspire",
      prodimage1: dell2,
      prodimage2: dell2,
      prodimage3: dell2,
      prodimage4: dell2,
      prodimage5: dell2,
      prodimage6: dell2,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 1003,
      name: "Dell Aspiron 5 pro",
      prodimage1: dell3,
      prodimage2: dell3,
      prodimage3: dell3,
      prodimage4: dell3,
      prodimage5: dell3,
      prodimage6: dell3,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 1004,
      name: "Dell Inspire",
      prodimage1: dell2,
      prodimage2: dell2,
      prodimage3: dell2,
      prodimage4: dell2,
      prodimage5: dell2,
      prodimage6: dell2,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 1005,
      name: "Dell Aspiron 5 pro",
      prodimage1: dell3,
      prodimage2: dell3,
      prodimage3: dell3,
      prodimage4: dell3,
      prodimage5: dell3,
      prodimage6: dell3,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },

    {
      id: 1100,
      name: "Lenvo Aspiron",
      prodimage1: lenvo1,
      prodimage2: lenvo1,
      prodimage3: lenvo1,
      prodimage4: lenvo1,
      prodimage5: lenvo1,
      prodimage6: lenvo1,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 1101,
      name: "Lenvo Aspiron",
      prodimage1: lenvo2,
      prodimage2: lenvo2,
      prodimage3: lenvo2,
      prodimage4: lenvo2,
      prodimage5: lenvo2,
      prodimage6: lenvo2,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 1103,
      name: "Lenvo Aspiron",
      prodimage1: lenvo3,
      prodimage2: lenvo3,
      prodimage3: lenvo3,
      prodimage4: lenvo3,
      prodimage5: lenvo3,
      prodimage6: lenvo3,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 1104,
      name: "Lenvo Aspiron",
      prodimage1: lenvo1,
      prodimage2: lenvo1,
      prodimage3: lenvo1,
      prodimage4: lenvo1,
      prodimage5: lenvo1,
      prodimage6: lenvo1,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 1105,
      name: "Lenvo Aspiron",
      prodimage1: lenvo2,
      prodimage2: lenvo2,
      prodimage3: lenvo2,
      prodimage4: lenvo2,
      prodimage5: lenvo2,
      prodimage6: lenvo2,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
    {
      id: 1106,
      name: "Lenvo Aspiron",
      prodimage1: lenvo3,
      prodimage2: lenvo3,
      prodimage3: lenvo3,
      prodimage4: lenvo3,
      prodimage5: lenvo3,
      prodimage6: lenvo3,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "450$",
      discountprice: "382$",
      quantity: 0,
    },
  ];
}