import denim from "../assests/clothes/denim.jpeg"
export function getClothesData(param) {
    return [
      {
        id: 10,
        name: "denim",
        prodimage1: denim,
        prodimage2: denim,
        prodimage3: denim,
        prodimage4: denim,
        prodimage5: denim,
        prodimage6: denim,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
      {
        id: 11,
        name: "asus k1",
        prodimage1: denim,
        prodimage2: denim,
        prodimage3: denim,
        prodimage4: denim,
        prodimage5: denim,
        prodimage6: denim,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
      {
        id: 12,
        name: "asus k15",
        prodimage1: denim,
        prodimage2: denim,
        prodimage3: denim,
        prodimage4: denim,
        prodimage5: denim,
        prodimage6: denim,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
      {
        id: 13,
        name: "asus k15",
        prodimage1: denim,
        prodimage2: denim,
        prodimage3: denim,
        prodimage4: denim,
        prodimage5: denim,
        prodimage6: denim,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
      {
        id: 14,
        name: "asus k15",
        prodimage1: denim,
        prodimage2: denim,
        prodimage3: denim,
        prodimage4: denim,
        prodimage5: denim,
        prodimage6: denim,
        desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
        price: "$380",
        quantity: 0,
      },
    ];
}