import toy from "../assests/kids/toy.jpg";
export function getToysData(param) {
  return [
    {
      id: 20,
      name: "transformer",
      prodimage1: toy,
      prodimage2: toy,
      prodimage3: toy,
      prodimage4: toy,
      prodimage5: toy,
      prodimage6: toy,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "$380",
      quantity: 0,
    },
    {
      id: 21,
      name: "asus k1",
      prodimage1: toy,
      prodimage2: toy,
      prodimage3: toy,
      prodimage4: toy,
      prodimage5: toy,
      prodimage6: toy,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "$380",
      quantity: 0,
    },
    {
      id: 22,
      name: "asus k15",
      prodimage1: toy,
      prodimage2: toy,
      prodimage3: toy,
      prodimage4: toy,
      prodimage5: toy,
      prodimage6: toy,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "$380",
      quantity: 0,
    },
    {
      id: 23,
      name: "asus k15",
      prodimage1: toy,
      prodimage2: toy,
      prodimage3: toy,
      prodimage4: toy,
      prodimage5: toy,
      prodimage6: toy,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "$380",
      quantity: 0,
    },
    {
      id: 24,
      name: "asus k15",
      prodimage1: toy,
      prodimage2: toy,
      prodimage3: toy,
      prodimage4: toy,
      prodimage5: toy,
      prodimage6: toy,
      desc: "8 GB RAM | 128 GB ROM16.64 cm (6.55 inch) Full HD+ 16MP Front Camera 4500 mAh Lithium-ion Snapdragon 778G+. Full HD OLED Display.",
      price: "$380",
      quantity: 0,
    },
  ];
}