import casual from "../assets/images/casual.jpg";
import check from "../assets/images/check.jpg";
import formal from "../assets/images/formal.webp";
import oppoA31 from "../assets/images/oppoA31.jpg";
export function BrowsingData(param) {
    return [
      
        {id:0,
            item1: casual,
            item2: "shirt ",
            item3:"it is pink shirt for men ",
            price:"200$",
            quantity:0,
            
          },
          {id:1,
            item1: check,
            item2: "check shirt",
            item3:"It is red check shirt",
            price:"200$",
            quantity:0,
            
          },
          {id:2,
            item1: formal,
            item2: "formal shirt",
            item3:"It is a formal wear",
            price:"200$",
            quantity:0,
            
          },
          {id:3,
            item1: oppoA31,
            item2: "Oppo phone",
            item3:"12MP Triple Rear Camera |Waterdrop Eye Protection Screen|4230mAh Battery|Fingerprint Unlock",
            price:"200$",
            quantity:0,
        },
            {id:4,
              item1: casual,
              item2: "shirt ",
              item3:"it is pink shirt for men ",
              price:"200$",
            quantity:0,
            },
            {id:5,
              item1: check,
              item2: "check shirt",
              item3:"It is red check shirt",
              price:"200$",
            quantity:0,
            },
            {id:6,
              item1: formal,
              item2: "formal shirt",
              item3:"It is a formal wear",
              price:"200$",
            quantity:0,
            },
            {id:7,
              item1: oppoA31,
              item2: "Oppo phone",
              item3:"12MP Triple Rear Camera |Waterdrop Eye Protection Screen|4230mAh Battery|Fingerprint Unlock",
              price:"200$",
              quantity:0,
            },
            
              {id:8,
                item1: casual,
                item2: "shirt ",
                item3:"it is pink shirt for men ",
                price:"200$",
            quantity:0,
              },
              {id:9,
                item1: check,
                item2: "check shirt",
                item3:"It is red check shirt",
                price:"200$",
            quantity:0,

              },
              {id:10,
                item1: formal,
                item2: "formal shirt",
                item3:"It is a formal wear",
                price:"200$",
            quantity:0,
              },
              {id:11,
                item1: oppoA31,
                item2: "Oppo phone",
                item3:"12MP Triple Rear Camera |Waterdrop Eye Protection Screen|4230mAh Battery|Fingerprint Unlock",
                price:"200$",
                quantity:0,
              },
                {id:12,
                  item1: casual,
                  item2: "shirt ",
                  item3:"it is pink shirt for men ",
                  price:"200$",
                  quantity:0,
                  
                },
                {id:13,
                  item1: check,
                  item2: "check shirt",
                  item3:"It is red check shirt",
                  price:"200$",
                  quantity:0,
                },
                {id:14,
                  item1: formal,
                  item2: "formal shirt",
                  item3:"It is a formal wear",
                  price:"400$",
                  
            quantity:0,
                },
                {id:15,
                  item1: oppoA31,
                  item2: "Oppo phone",
                  item3:"12MP Triple Rear Camera |Waterdrop Eye Protection Screen|4230mAh Battery|Fingerprint Unlock",
                  price:"200$",
            quantity:0,},
                
    ];
}